# encoding: utf-8

chile2001 = {

    ("Santiago Morning",       "Huachipato"):             (2,  2),
    ("O'Higgins",              "Santiago Wanderers"):     (0,  5),
    ("Colo Colo",              "Deportes Puerto Montt"):  (2,  0),
    ("Unión San Felipe",       "Cobreloa"):               (1,  1),
    ("Deportes Concepción",    "Rangers"):                (0,  1),
    ("Audax Italiano",         "Universidad Católica"):   (0,  2),
    ("Unión Española",         "Palestino"):              (1,  2),
    ("Coquimbo Unido",         "Universidad de Chile"):   (2,  1),

    ("Unión San Felipe",       "O'Higgins"):              (5,  1),
    ("Cobreloa",               "Unión Española"):         (1,  1),
    ("Palestino",              "Coquimbo Unido"):         (0,  1),
    ("Universidad de Chile",   "Deportes Concepción"):    (4,  0),
    ("Rangers",                "Santiago Morning"):       (3,  1),
    ("Deportes Puerto Montt",  "Audax Italiano"):         (1,  0),
    ("Huachipato",             "Colo Colo"):              (1,  0),
    ("Universidad Católica",   "Santiago Wanderers"):     (2,  2),

    ("Coquimbo Unido",         "Cobreloa"):               (2,  1),
    ("O'Higgins",              "Universidad Católica"):   (4,  1),
    ("Unión Española",         "Unión San Felipe"):       (2,  1),
    ("Colo Colo",              "Rangers"):                (5,  3),
    ("Santiago Morning",       "Universidad de Chile"):   (3,  4),
    ("Deportes Concepción",    "Palestino"):              (1,  2),
    ("Santiago Wanderers",     "Deportes Puerto Montt"):  (2,  0),
    ("Audax Italiano",         "Huachipato"):             (0,  0),

    ("Universidad de Chile",   "Colo Colo"):              (1,  1),
    ("Unión San Felipe",       "Coquimbo Unido"):         (4,  1),
    ("Cobreloa",               "Deportes Concepción"):    (1,  2),
    ("Palestino",              "Santiago Morning"):       (1,  0),
    ("Deportes Puerto Montt",  "Universidad Católica"):   (2,  5),
    ("Huachipato",             "Santiago Wanderers"):     (3,  4),
    ("Unión Española",         "O'Higgins"):              (2,  1),
    ("Rangers",                "Audax Italiano"):         (1,  2),

    ("Santiago Morning",       "Cobreloa"):               (1,  2),
    ("Audax Italiano",         "Universidad de Chile"):   (2,  3),
    ("Coquimbo Unido",         "Unión Española"):         (0,  1),
    ("Universidad Católica",   "Huachipato"):             (2,  1),
    ("Colo Colo",              "Palestino"):              (2,  0),
    ("Santiago Wanderers",     "Rangers"):                (1,  1),
    ("Deportes Concepción",    "Unión San Felipe"):       (1,  1),
    ("O'Higgins",              "Deportes Puerto Montt"):  (2,  3),

    ("Unión Española",         "Deportes Concepción"):    (2,  1),
    ("Unión San Felipe",       "Santiago Morning"):       (1,  0),
    ("Palestino",              "Audax Italiano"):         (1,  0),
    ("Rangers",                "Universidad Católica"):   (0,  0),
    ("Coquimbo Unido",         "O'Higgins"):              (1,  2),
    ("Cobreloa",               "Colo Colo"):              (2,  0),
    ("Universidad de Chile",   "Santiago Wanderers"):     (0,  0),
    ("Huachipato",             "Deportes Puerto Montt"):  (3,  1),

    ("Audax Italiano",         "Cobreloa"):               (1,  0),
    ("O'Higgins",              "Huachipato"):             (0,  4),
    ("Deportes Concepción",    "Coquimbo Unido"):         (1,  2),
    ("Colo Colo",              "Unión San Felipe"):       (4,  1),
    ("Santiago Morning",       "Unión Española"):         (3,  5),
    ("Deportes Puerto Montt",  "Rangers"):                (1,  1),
    ("Universidad Católica",   "Universidad de Chile"):   (0,  1),
    ("Santiago Wanderers",     "Palestino"):              (2,  0),

    ("Unión Española",         "Colo Colo"):              (3,  3),
    ("Rangers",                "Huachipato"):             (1,  1),
    ("Palestino",              "Universidad Católica"):   (3,  2),
    ("Coquimbo Unido",         "Santiago Morning"):       (3,  0),
    ("Unión San Felipe",       "Audax Italiano"):         (1,  0),
    ("Universidad de Chile",   "Deportes Puerto Montt"):  (3,  1),
    ("Deportes Concepción",    "O'Higgins"):              (1,  0),
    ("Cobreloa",               "Santiago Wanderers"):     (3,  0),

    ("Universidad Católica",   "Cobreloa"):               (0,  1),
    ("Huachipato",             "Universidad de Chile"):   (1,  2),
    ("Santiago Morning",       "Deportes Concepción"):    (1,  2),
    ("Colo Colo",              "Coquimbo Unido"):         (0,  0),
    ("O'Higgins",              "Rangers"):                (0,  0),
    ("Deportes Puerto Montt",  "Palestino"):              (0,  1),
    ("Audax Italiano",         "Unión Española"):         (3,  2),
    ("Santiago Wanderers",     "Unión San Felipe"):       (2,  0),

    ("Unión San Felipe",       "Universidad Católica"):   (1,  0),
    ("Coquimbo Unido",         "Audax Italiano"):         (1,  0),
    ("Unión Española",         "Santiago Wanderers"):     (0,  2),
    ("Palestino",              "Huachipato"):             (2,  0),
    ("Universidad de Chile",   "Rangers"):                (1,  0),
    ("Cobreloa",               "Deportes Puerto Montt"):  (3,  1),
    ("Deportes Concepción",    "Colo Colo"):              (2,  2),
    ("Santiago Morning",       "O'Higgins"):              (4,  1),

    ("O'Higgins",              "Universidad de Chile"):   (0,  2),
    ("Deportes Puerto Montt",  "Unión San Felipe"):       (1,  1),
    ("Colo Colo",              "Santiago Morning"):       (2,  1),
    ("Universidad Católica",   "Unión Española"):         (5,  1),
    ("Audax Italiano",         "Deportes Concepción"):    (0,  2),
    ("Huachipato",             "Cobreloa"):               (0,  0),
    ("Santiago Wanderers",     "Coquimbo Unido"):         (1,  1),
    ("Rangers",                "Palestino"):              (2,  3),

    ("Coquimbo Unido",         "Universidad Católica"):   (0,  1),
    ("Unión San Felipe",       "Huachipato"):             (3,  2),
    ("Palestino",              "Universidad de Chile"):   (1,  4),
    ("Santiago Morning",       "Audax Italiano"):         (0,  3),
    ("Colo Colo",              "O'Higgins"):              (2,  0),
    ("Deportes Concepción",    "Santiago Wanderers"):     (2,  0),
    ("Unión Española",         "Deportes Puerto Montt"):  (4,  1),
    ("Cobreloa",               "Rangers"):                (1,  0),

    ("Santiago Wanderers",     "Santiago Morning"):       (3,  1),
    ("Deportes Puerto Montt",  "Coquimbo Unido"):         (1,  1),
    ("O'Higgins",              "Palestino"):              (4,  3),
    ("Universidad Católica",   "Deportes Concepción"):    (2,  0),
    ("Universidad de Chile",   "Cobreloa"):               (1,  1),
    ("Rangers",                "Unión San Felipe"):       (2,  1),
    ("Huachipato",             "Unión Española"):         (2,  2),
    ("Audax Italiano",         "Colo Colo"):              (0,  3),

    ("Santiago Morning",       "Universidad Católica"):   (2,  2),
    ("Deportes Concepción",    "Deportes Puerto Montt"):  (3,  0),
    ("Coquimbo Unido",         "Huachipato"):             (0,  3),
    ("Unión Española",         "Rangers"):                (2,  2),
    ("Cobreloa",               "Palestino"):              (3,  1),
    ("Colo Colo",              "Santiago Wanderers"):     (1,  0),
    ("Audax Italiano",         "O'Higgins"):              (2,  1),
    ("Unión San Felipe",       "Universidad de Chile"):   (1,  1),

    ("O'Higgins",              "Cobreloa"):               (1,  1),
    ("Palestino",              "Unión San Felipe"):       (0,  0),
    ("Universidad de Chile",   "Unión Española"):         (4,  0),
    ("Santiago Wanderers",     "Audax Italiano"):         (1,  0),
    ("Huachipato",             "Deportes Concepción"):    (2,  2),
    ("Universidad Católica",   "Colo Colo"):              (1,  1),
    ("Deportes Puerto Montt",  "Santiago Morning"):       (0,  0),
    ("Rangers",                "Coquimbo Unido"):         (3,  0),

    ("Universidad Católica",   "Audax Italiano"):         (2,  0),
    ("Deportes Puerto Montt",  "Colo Colo"):              (3,  2),
    ("Universidad de Chile",   "Coquimbo Unido"):         (0,  2),
    ("Cobreloa",               "Unión San Felipe"):       (1,  0),
    ("Rangers",                "Deportes Concepción"):    (1,  2),
    ("Huachipato",             "Santiago Morning"):       (4,  1),
    ("Palestino",              "Unión Española"):         (2,  2),
    ("Santiago Wanderers",     "O'Higgins"):              (2,  1),

    ("Colo Colo",              "Huachipato"):             (2,  1),
    ("O'Higgins",              "Unión San Felipe"):       (4,  3),
    ("Unión Española",         "Cobreloa"):               (1,  1),
    ("Santiago Wanderers",     "Universidad Católica"):   (1,  3),
    ("Coquimbo Unido",         "Palestino"):              (0,  0),
    ("Audax Italiano",         "Deportes Puerto Montt"):  (2,  0),
    ("Deportes Concepción",    "Universidad de Chile"):   (2,  2),
    ("Santiago Morning",       "Rangers"):                (2,  1),

    ("Universidad Católica",   "O'Higgins"):              (4,  0),
    ("Cobreloa",               "Coquimbo Unido"):         (3,  2),
    ("Palestino",              "Deportes Concepción"):    (1,  0),
    ("Huachipato",             "Audax Italiano"):         (3,  1),
    ("Deportes Puerto Montt",  "Santiago Wanderers"):     (3,  3),
    ("Universidad de Chile",   "Santiago Morning"):       (0,  1),
    ("Unión San Felipe",       "Unión Española"):         (3,  0),
    ("Rangers",                "Colo Colo"):              (1,  1),

    ("Deportes Concepción",    "Cobreloa"):               (0,  0),
    ("Coquimbo Unido",         "Unión San Felipe"):       (0,  0),
    ("O'Higgins",              "Unión Española"):         (1,  2),
    ("Universidad Católica",   "Deportes Puerto Montt"):  (4,  0),
    ("Santiago Morning",       "Palestino"):              (2,  3),
    ("Santiago Wanderers",     "Huachipato"):             (4,  2),
    ("Audax Italiano",         "Rangers"):                (2,  1),
    ("Colo Colo",              "Universidad de Chile"):   (2,  3),

    ("Palestino",              "Colo Colo"):              (0,  2),
    ("Unión San Felipe",       "Deportes Concepción"):    (2,  0),
    ("Huachipato",             "Universidad Católica"):   (1,  1),
    ("Deportes Puerto Montt",  "O'Higgins"):              (0,  2),
    ("Unión Española",         "Coquimbo Unido"):         (1,  0),
    ("Rangers",                "Santiago Wanderers"):     (1,  1),
    ("Cobreloa",               "Santiago Morning"):       (5,  0),
    ("Universidad de Chile",   "Audax Italiano"):         (1,  0),

    ("Colo Colo",              "Cobreloa"):               (1,  0),
    ("Universidad Católica",   "Rangers"):                (3,  1),
    ("Deportes Puerto Montt",  "Huachipato"):             (0,  3),
    ("O'Higgins",              "Coquimbo Unido"):         (0,  1),
    ("Audax Italiano",         "Palestino"):              (1,  2),
    ("Santiago Wanderers",     "Universidad de Chile"):   (4,  1),
    ("Deportes Concepción",    "Unión Española"):         (5,  2),
    ("Santiago Morning",       "Unión San Felipe"):       (1,  1),

    ("Universidad de Chile",   "Universidad Católica"):   (0,  1),
    ("Coquimbo Unido",         "Deportes Concepción"):    (2,  0),
    ("Unión Española",         "Santiago Morning"):       (0,  3),
    ("Palestino",              "Santiago Wanderers"):     (1,  2),
    ("Cobreloa",               "Audax Italiano"):         (1,  0),
    ("Huachipato",             "O'Higgins"):              (2,  1),
    ("Rangers",                "Deportes Puerto Montt"):  (2,  0),
    ("Unión San Felipe",       "Colo Colo"):              (2,  2),

    ("Deportes Puerto Montt",  "Universidad de Chile"):   (0,  2),
    ("Universidad Católica",   "Palestino"):              (0,  0),
    ("O'Higgins",              "Deportes Concepción"):    (1,  1),
    ("Santiago Morning",       "Coquimbo Unido"):         (3,  1),
    ("Colo Colo",              "Unión Española"):         (5,  1),
    ("Audax Italiano",         "Unión San Felipe"):       (0,  2),
    ("Huachipato",             "Rangers"):                (2,  1),
    ("Santiago Wanderers",     "Cobreloa"):               (3,  0),

    ("Rangers",                "O'Higgins"):              (2,  1),
    ("Deportes Concepción",    "Santiago Morning"):       (0,  0),
    ("Unión Española",         "Audax Italiano"):         (0,  1),
    ("Cobreloa",               "Universidad Católica"):   (0,  1),
    ("Palestino",              "Deportes Puerto Montt"):  (2,  2),
    ("Unión San Felipe",       "Santiago Wanderers"):     (1,  2),
    ("Coquimbo Unido",         "Colo Colo"):              (1,  3),
    ("Universidad de Chile",   "Huachipato"):             (0,  0),

    ("Colo Colo",              "Deportes Concepción"):    (4,  0),
    ("O'Higgins",              "Santiago Morning"):       (2,  3),
    ("Rangers",                "Universidad de Chile"):   (0,  2),
    ("Santiago Wanderers",     "Unión Española"):         (2,  1),
    ("Huachipato",             "Palestino"):              (1,  2),
    ("Deportes Puerto Montt",  "Cobreloa"):               (1,  1),
    ("Universidad Católica",   "Unión San Felipe"):       (1,  0),
    ("Audax Italiano",         "Coquimbo Unido"):         (1,  0),

    ("Coquimbo Unido",         "Santiago Wanderers"):     (0,  1),
    ("Unión San Felipe",       "Deportes Puerto Montt"):  (2,  2),
    ("Universidad de Chile",   "O'Higgins"):              (3,  2),
    ("Palestino",              "Rangers"):                (5,  1),
    ("Cobreloa",               "Huachipato"):             (0,  3),
    ("Santiago Morning",       "Colo Colo"):              (3,  3),
    ("Deportes Concepción",    "Audax Italiano"):         (1,  2),
    ("Unión Española",         "Universidad Católica"):   (0,  1),

    ("Universidad Católica",   "Coquimbo Unido"):         (3,  0),
    ("Rangers",                "Cobreloa"):               (2,  2),
    ("Deportes Puerto Montt",  "Unión Española"):         (2,  3),
    ("Universidad de Chile",   "Palestino"):              (3,  1),
    ("Santiago Wanderers",     "Deportes Concepción"):    (5,  1),
    ("Huachipato",             "Unión San Felipe"):       (2,  1),
    ("O'Higgins",              "Colo Colo"):              (4,  2),
    ("Audax Italiano",         "Santiago Morning"):       (1,  1),

    ("Deportes Concepción",    "Universidad Católica"):   (0,  4),
    ("Colo Colo",              "Audax Italiano"):         (2,  1),
    ("Unión San Felipe",       "Rangers"):                (2,  2),
    ("Coquimbo Unido",         "Deportes Puerto Montt"):  (2,  2),
    ("Palestino",              "O'Higgins"):              (2,  2),
    ("Cobreloa",               "Universidad de Chile"):   (0,  1),
    ("Santiago Morning",       "Santiago Wanderers"):     (1,  5),
    ("Unión Española",         "Huachipato"):             (2,  4),

    ("Universidad Católica",   "Santiago Morning"):       (6,  3),
    ("Palestino",              "Cobreloa"):               (1,  2),
    ("Deportes Puerto Montt",  "Deportes Concepción"):    (2,  0),
    ("Rangers",                "Unión Española"):         (1,  1),
    ("Universidad de Chile",   "Unión San Felipe"):       (2,  3),
    ("Huachipato",             "Coquimbo Unido"):         (2,  2),
    ("O'Higgins",              "Audax Italiano"):         (1,  0),
    ("Santiago Wanderers",     "Colo Colo"):              (1,  0),

    ("Coquimbo Unido",         "Rangers"):                (1,  1),
    ("Unión San Felipe",       "Palestino"):              (1,  2),
    ("Unión Española",         "Universidad de Chile"):   (2,  1),
    ("Deportes Concepción",    "Huachipato"):             (3,  3),
    ("Santiago Morning",       "Deportes Puerto Montt"):  (4,  1),
    ("Cobreloa",               "O'Higgins"):              (2,  0),
    ("Audax Italiano",         "Santiago Wanderers"):     (2,  4),
    ("Colo Colo",              "Universidad Católica"):   (4,  1),

}
